//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnoses
    {
        public int Id { get; set; }
        public string Symptoms { get; set; }
        public string Diagnossis { get; set; }
        public string Medicines { get; set; }
        public Nullable<int> DoctorId { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
