//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital_new
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int Id { get; set; }
        public string PatientName { get; set; }
        public string PatientAdresses { get; set; }
        public string PatientPhone { get; set; }
        public int PatientAge { get; set; }
        public int Gender { get; set; }
        public int BloodGroup { get; set; }
        public string PatientDisease { get; set; }
        public int DoctorId { get; set; }
    
        public virtual Diagnoses Diagnoses { get; set; }
        public virtual Doctors Doctors { get; set; }
    }
}
